// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwytalxifmbbtuscarxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eXRhbHhpZm1iYnR1c2Nhcnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MjMzNTcsImV4cCI6MjA1MjE5OTM1N30.gPlhBgfnXeIN0gPDTTWCJHD9ArpiozVFEm4r-I9fGas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);